### ISSUE TITLE
dependencies for product_issue and document

### ISSUE THREAD

**Issue by zachary** [mcb30/odoo-edi#2]
i cannot install the module because missing modules as below, please advise it.

project_issue | Unknown
document | Not Installed

**Comment by mcb30** [comment]
Which version of Odoo are you using?

**Comment by zachary** [comment]
Hi Michael,

Thanks for your updated.

I use Odoo 11 currently, it looks like 'Issue Tracker' module is not opened
source in Odoo 11, am I right? Could you please let me know if any solution
for this you have?

Thanks in advance.
Sincerely
Zachary

**Comment by mcb30** [comment]
The "project_issue" module was removed because the functionality was merged into the base "project" module.

I have pushed an (untested) initial work-in-progress branch called "wip11" which installs cleanly under Odoo 11.  Please be aware that this branch has not yet been tested.

**Comment by mcb30** [comment]
The module is now fully updated for Odoo 11.
