### ISSUE TITLE
Which odoo version is this module working for?

### ISSUE THREAD

**Issue by ZOOUQinn** [mcb30/odoo-edi#3]
Please advise.

ZOOU Qinn

**Comment by mcb30** [comment]
It was written for Odoo 10.  I am aware of ongoing work to update it for Odoo 11.

**Comment by ZOOUQinn** [comment]
Hey Michael,

I get errors when installing you module on Odoo 10:

```
ParseError: "External ID not found in the system: edi.sequence_default" while parsing file:///e:/workspace/odoo10/zqinnaddons/odoo-edi/data/edi_document_data.xml:13

ParseError: "External ID not found in the system: edi.project_default" while parsing file:///e:/workspace/odoo10/zqinnaddons/odoo-edi/data/edi_gateway_local_data.xml:6

ParseError: "External ID not found in the system: edi.project_default" while parsing file:///e:/workspace/odoo10/zqinnaddons/odoo-edi/data/edi_gateway_mail_data.xml:6

ParseError: "External ID not found in the system: edi.project_default" while parsing file:///e:/workspace/odoo10/zqinnaddons/odoo-edi/data/edi_gateway_xmlrpc_data.xml:6
```

Would you please test your module on a new created database?

Maybe you didn't define the records with External ID of "edi.sequence_default" and "edi.project_default" in you code, but they can be found in your developing database currently for some reason?

**Comment by mcb30** [comment]
On 26/05/18 08:01, ZOOUQinn wrote:
> I get errors when installing you module on Odoo 10:
 >
 > <snip>
> 
> Would you please test your module on a new created database?

It works for me.  From a completely empty database, installed using:

   ./odoo-bin -d odoo -i edi --without-demo=all

> Maybe you didn't define the records with External ID of 
> "edi.sequence_default" and "edi.project_default" in you code, but they 
> can be found in you developing database currently for some reason?

Those records are defined in data/edi_document_data.xml and 
data/project_issue_data.xml respectively.

Michael

**Comment by mcb30** [comment]
This was using commit https://github.com/odoo/odoo/commit/3051d1d (i.e. the current "10.0" branch).

Michael

**Comment by mcb30** [comment]
Also tested installing into a freshly created database via the web UI.  All works as expected.

Michael

**Comment by mcb30** [comment]
BTW, I have pushed some work-in-progress for the Odoo 11 port to the "wip11" branch.  This is sufficient to at least get the module installed under Odoo 11.

**Comment by ZOOUQinn** [comment]
Hey Michael,

I cloned your code with url list on your module's page and get the directory with name "odoo-edi" (a.k.a, module's technical name).
Then I got some idea from your command that installing this module, changed the name of this directory to "edi". Everything is workable after this modifying.

So, you should better to modify the technical name.

Qinn

**Comment by mcb30** [comment]
Thanks for the information.  I have recreated the history (using git-filter-branch) so that every file is now within an "addons/edi" subdirectory.  I wouldn't normally rewrite history for a published branch in this way, but I think it's reasonably safe since this module has only just been released and is still in the process of being updated for the current version of Odoo.
